//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiometricAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int SN { get; set; }
        public string StudentID { get; set; }
        public string MatricNumber { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Department { get; set; }
        public string StudentLevel { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneType { get; set; }
        public string PhoneModel { get; set; }
        public string PhoneIMEI { get; set; }
        public string LaptopType { get; set; }
        public string LaptopModel { get; set; }
        public string LaptopSerialNumber { get; set; }
        public string pictureURL { get; set; }
        public string status { get; set; }
        public string Degree_Type { get; set; }
        public string Hostel { get; set; }
        public Nullable<int> Room_number { get; set; }
        public string Gender { get; set; }
    }
}
