//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiometricAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int SN { get; set; }
        public string UserID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string AdminType { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string email_code { get; set; }
    }
}
