//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiometricAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int SN { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string DATE_OF_VISIT { get; set; }
        public string WHOM_TO_SEE { get; set; }
        public string TIME_IN { get; set; }
        public string TIME_OUT { get; set; }
    }
}
